### ISSUE TITLE
Posting an unsupported link is weird

### ISSUE THREAD

**Issue by ticky** [foozmeat/tusk.rocks#7]
Pasting, for instance, a Bandcamp link, will preview saying no preview could be found, but still allows the user to submit.

This does in fact post to Mastodon, but the view on Tusk is unusable as no link is presented (sorry for double-posting):
<img width="461" alt="image" src="https://user-images.githubusercontent.com/282113/45191052-eca2db80-b1f5-11e8-91f1-247305e9cbfc.png">

**Comment by foozmeat** [comment]
Yeah, I need to go out to the linked site and grab it's opengraph/twitter card data to get a good representation in this case. Thank you for filing this.

**Comment by foozmeat** [comment]
This should be better now. I added explicit support for bandcamp and soundcloud URLs
